---
title: "Untitled"
author: "Kija"
date: "`r Sys.Date()`"
output: html_document


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# course part 1 - Laboratory
- we selected 20 isolates
- 6 isolates are ***Klebsiella spp***._ isolates
- isolates are *Escherichia coli*_ isolates 
- 8 isolates are *salmonella spp*_ isolates

ctrl+alt+I (make a cell - shortcut on the keyboard)

```{r}
angry_or_not <- "not"
```

Madelaine, are your angry or not? `r (angry_or_not)`

#working with your data

```{r}
here::here()
```

```{r}
path_data <- here::here("data/2024-09-25_INIKA_SAMPLING_ANALYSIS_HUMAN.csv")

path_data
```

```{r}
human_data <-
  readr::read_csv2(path_data)
```
For`; delimited files its read_csv2 function
For`,`delimited files its read_csv function
---
# Day 3

## packages into memory
```{r}
?library()
help("library")
```

## we get out data
```{r}
path_data <- here::here("data/2024-09-25_INIKA_SAMPLING_ANALYSIS_HUMAN.csv")

path_data
```
```{r}
human_data <-
  readr::read_csv2(path_data)
```

- Names of columns

```{r}
colnames(human_data)
```

- getting the columns into a vector for pasting and manipulations

```{r}
dput(
  colnames(human_data)
  )
```

- exploration: c() is to make vectors

```{r}
test <- c("one", "2', 3")
test
test[3]
typeof(test)

class(test)
```

All the elements of a vector are of the same 'type' (text, double = Real, interger, date ...)

```{r}
test2 <-c(1,2,3)
typeof(test2)
typeof(test2 * test2)
class(test2)
```

```{r}
test2 * test2
```

```{r}
test2 * c(1,2,3)
```

- overview of data and data types
```{r}
glimpse(human_data)
str(human_data)
```



