---
title: "22_11_24_Practical"
author: "Kija"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing data saved as rds (r file format)

object_name <- readRDS("path/to/file_name.rds")

```{r}
library(tidyverse)
```

```{r}
?filter()
?stats::filter()
?dplyr::filter()
```


```{r}
here::here("data","human_data_selection_dedup.rds")
human_data_selection <- readRDS(here::here("data","human_data_selection_dedup.rds"))
```

# connection to the database in WHONET


```{r}
#install.packages("RSQLite")
library(RSQLite)
```


```{r}
sqlite_path <- here::here("C:/WHONET/Data/TZA-INIKA_TZ-2024.sqlite")
sqlite_path
dbconn <- DBI::dbConnect(RSQLite::SQLite(), sqlite_path) 
```

```{r}
dbconn
```

```{r}
dbListTables(dbconn)
```

```{r}
library(tidyverse)
mydata_recipie <- tbl(dbconn, "isolates")
str(mydata_recipie)
head(mydata_recipie)
```


```{r}
show_query(mydata_recipie)
```

```{r}
mydata <- mydata_recipie %>% collect()
```

```{r}
?dplyr::join
```

```{r}
#my_innerjoin <- 
human_selection %>%
  # selecting few columns for testing 
  # this can be used to do a  short selection of the column 
  if not all are required 
select(1:3) %>%
dplyr::inner_join(mydata, by = c(INIKA_OH_TZ_ID" = "PATIENT_ID)) %>%
head() %>%
view()
```

would it work

```{r}
mydata %>%
  dplyr::inner_join(
    human_selection %>% selection (1:3), by = c("pPATIENT_ID" = "INIKA_OH_TZ_ID")) %>%
  head() %>%
  view()

```

